Exercise 0 - Example

In [2]:
q = 31
q**4

923521

Exercise 1

In [3]:
#creating arbitrary list
def f(a, *arguments):
    print(a)
    for arg in arguments:
        print(arg)
f("A", "B", "C")

A
B
C


In [4]:
#Creating a tuple
tup1=(1, 2, 3, 4, 5, 6, 7)
print(tup1)

(1, 2, 3, 4, 5, 6, 7)


In [5]:
# Creating a Dictionary
Dict = {1: 'Creating', 2: 'A', 3: 'Dictionary'}
print(Dict)

{1: 'Creating', 2: 'A', 3: 'Dictionary'}


Exercise 2

In [6]:
import numpy as np
s = np.random.normal(0,1,100)


In [7]:
#the 10th element
print(s[9])

0.3357381974690766


In [8]:
#printing elements from 10 to 20
print(s[9:19])

[ 0.3357382  -0.90225819  0.77287096  1.01693612 -0.4954645   1.10819112
  1.42013007 -2.16181079  0.62707285  0.2491214 ]


In [9]:
#printing elements more than 0
def printAbove(s, a):
    for i in range(a):
        if s[i] > 0:
            print(s[i], end = " ")
a = len(s)
printAbove(s, a)

0.390477132961993 0.2004280226037637 1.5864935938136624 0.8772151155088465 0.3357381974690766 0.7728709603299836 1.0169361202859415 1.1081911238745283 1.420130073962761 0.62707284684786 0.24912139670009298 1.1292654335604826 0.5050870704934585 2.1057357168348774 2.6421921581822363 0.5815226090369866 1.2817999108589875 0.4306332335488303 0.948688730340022 1.8793235052555493 0.10801353371367214 1.6234593287353947 0.10245191582406828 0.32648054722925135 1.2411767539911287 0.32127371657163445 0.7810629814088195 0.6447108322262459 1.0138237824927063 0.8471154691743915 0.17927925983612877 0.0060091220165670945 0.8199819862443474 0.11947441224825005 0.099253369013021 0.47636984417513595 1.0409306983284028 1.3021505978706425 0.3405823786298658 0.7617126288520553 0.7873250170163165 0.5269310731380218 0.21779292393982858 0.5290580152100736 0.515561526625441 2.241862186797138 1.4918411331099524 0.3025750512961358 0.08624756129329672 1.2016253123026384 0.795993855555012 

In [10]:
#2nd variant of printing elements more than 0
print(s[s>0])

[0.39047713 0.20042802 1.58649359 0.87721512 0.3357382  0.77287096
 1.01693612 1.10819112 1.42013007 0.62707285 0.2491214  1.12926543
 0.50508707 2.10573572 2.64219216 0.58152261 1.28179991 0.43063323
 0.94868873 1.87932351 0.10801353 1.62345933 0.10245192 0.32648055
 1.24117675 0.32127372 0.78106298 0.64471083 1.01382378 0.84711547
 0.17927926 0.00600912 0.81998199 0.11947441 0.09925337 0.47636984
 1.0409307  1.3021506  0.34058238 0.76171263 0.78732502 0.52693107
 0.21779292 0.52905802 0.51556153 2.24186219 1.49184113 0.30257505
 0.08624756 1.20162531 0.79599386]


Exercise 3

In [19]:
def mypow(base,power):
    if power<50:
        return base**power
    if power>=50:
        print ("Power is too big")
        return -1
  

print(mypow(2,3))
print(" ")
print(mypow(2,50))

8
 
Power is too big
-1


Exercise 4

In [12]:
import numpy as np
a=np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [13]:
def above(x,n):
    for i in x:
        if x[i] > n:
            print(x[i], end=" ")
            
print(above(a, 10))

       

11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 None


Exercise 5

In [14]:
import numpy as np
b=np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
def my_ifelse(x,exp,n):
    if exp == ">":
       return x[x>n]
    if exp == "<":
       return x[x<n]
    if exp == ">=":
       return x[x>=n]
    if exp == "<=":
       return x[x<=n]
    if exp == "==":
       return x[x==n]
    else: return x

    
print(my_ifelse(b,">=",17))
print(my_ifelse(b,"x",3))

[17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Exercise 6

In [16]:
def counter (input_string):
    count_letters = {}
    for letter in input_string:
        if letter in count_letters:
                count_letters[letter] += 1
        else:
            count_letters[letter] = 1
    return count_letters

print(counter ("kateryna"))

{'a': 3, 'l': 1, 'e': 1, 'k': 1, 's': 1, 'n': 1, 'd': 1, 'r': 1}


Exercise 7

In [17]:
def counter_sorted (input_string,reverse):
    a = {}
    for letter in sorted(input_string,reverse=reverse):
        if letter in a:
                a[letter] += 1 
        else:
            a[letter] = 1
    return a


print(counter_sorted("kateryna",False))
print(counter_sorted("kateryna",True))

{'a': 3, 'd': 1, 'e': 1, 'k': 1, 'l': 1, 'n': 1, 'r': 1, 's': 1}
{'s': 1, 'r': 1, 'n': 1, 'l': 1, 'k': 1, 'e': 1, 'd': 1, 'a': 3}
